#!/bin/bash

# PERMANENT FIX: Add mcpConfigPath to .local.xml (not auto-regenerated by Rider)
# This uses JetBrains' standard pattern for user-specific overrides

set -e

CONFIG_FILE="$HOME/.config/JetBrains/Rider2025.3/options/github-copilot.local.xml"
MCP_CONFIG_PATH="$HOME/.config/github-copilot/intellij/mcp.json"

echo "🔧 Adding MCP Config Path to GitHub Copilot .local.xml"
echo "   (This file is NOT auto-regenerated by Rider)"
echo ""

# Backup if exists
if [ -f "$CONFIG_FILE" ]; then
    cp "$CONFIG_FILE" "$CONFIG_FILE.backup"
    echo "📦 Backed up: $CONFIG_FILE.backup"
fi

# Create/update the .local.xml file
mkdir -p "$(dirname "$CONFIG_FILE")"

# Check if file exists and has github-copilot component already
if [ -f "$CONFIG_FILE" ] && grep -q '<component name="github-copilot">' "$CONFIG_FILE"; then
    echo "✅ github-copilot component already exists in .local.xml"
else
    # Add the component (preserving existing content if any)
    if [ -f "$CONFIG_FILE" ]; then
        # Insert before closing </application> tag
        sed -i 's|</application>|  <component name="github-copilot">\n    <option name="mcpConfigPath" value="'"$MCP_CONFIG_PATH"'" />\n  </component>\n</application>|' "$CONFIG_FILE"
        echo "✅ Added github-copilot component to existing .local.xml"
    else
        # Create new file
        cat > "$CONFIG_FILE" << EOF
<application>
  <component name="github-copilot">
    <option name="mcpConfigPath" value="$MCP_CONFIG_PATH" />
  </component>
</application>
EOF
        echo "✅ Created new .local.xml with mcpConfigPath"
    fi
fi

echo ""
echo "📄 Current config:"
cat "$CONFIG_FILE"
echo ""

# Verify
if grep -q "mcpConfigPath" "$CONFIG_FILE"; then
    echo "✅ SUCCESS! mcpConfigPath is in .local.xml"
    echo ""
    echo "📘 About .local.xml files:"
    echo "   • JetBrains uses .local.xml for user-specific overrides"
    echo "   • These files are NOT auto-regenerated on startup"
    echo "   • Settings here override the main config file"
    echo ""
    echo "Next steps:"
    echo "  1. Restart Rider (if running)"
    echo "  2. Open NEW Copilot chat (+ button)"
    echo "  3. Ask: 'list available agents'"
    echo ""
    echo "✨ This should be PERMANENT - Rider won't overwrite it!"
else
    echo "❌ ERROR: Failed to add mcpConfigPath"
    exit 1
fi

